# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the Node.js image as the base image
FROM node:18-alpine AS builder

# Set the working directory inside the Docker image
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application source code to the working directory
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript code
RUN npm run build

# Use a smaller Node.js image for the final release
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package-lock.json /app/node_modules ./ 

# Define the environment variable if necessary (adjust according to the app's requirements)
ENV NODE_ENV=production

# Define the command to run the application
ENTRYPOINT ["node", "dist/src/index.js"]